name: flutter_bloc_tutorial
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: null
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_bloc: null

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
