name: bloc_api_graphql
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.8
  google_fonts: ^6.1.0
  graphql: ^5.2.0-beta.6
  graphql_codegen: ^0.13.10
  graphql_flutter: ^5.2.0-beta.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
